### PR TITLE
landing Page

### PR DESCRIPTION
**Pull request by bdllhdrss3**
**Explain what this PR does?**

Summarise the main tasks handled in the pull request

**Propose Change**

- [ ] Bug fix (fixes an issue)
- [ ] Chore (small new feature added to the project)
- [X] New feature (change adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

**Motivation? (required)**

This is a landing page,it will act as a home page for raedar web
Screenshot (17)
Screenshot (18)
Screenshot (19)
Screenshot (20)
Screenshot (21)
Screenshot (22)
Screenshot (19) - Copy
Screenshot (19)
Screenshot (20) - Copy
Screenshot (20)

**Provide test plan?(required)**

Give bullet point instructions on how to setup the code and test it manually (Assume no prior experience on JS or code). See [What is a Test Plan?][1] to learn more.

**Any background context you want to provide?**

Any pertinent information that should be considered

**What are the relevant Trello/Pivotal/Jira/Github Issues?**

[#00000000](https://www.pivotaltracker.com/story/show/00000000)

**Screenshots (if appropriate)**

Original                   |     Updated
:--------------------------:|:-------------------------------:
** Original sreen short**   |** Updated sreen shot**

**Questions:**

If something is unclear or you want some questions to be addressed, mention them here

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9

### CODE REVIEW

**Comment by huxaiphaer** [comment]
Very Good work, but am still wondering why the build fails

**Comment by bdllhdrss3** [comment]
> Very Good work, but am still wondering why the build fails

i have fixed the vulnerabilities which were causing the problem

**Comment by huxaiphaer** [comment]
@FahdJamy , should we merge this for now ?

**Review by fahdjamy — APPROVED** [review]
Yeah, for now, I think we should merge this in.

**Pull request merged**
