### PR TITLE
navbar-footer

### PR DESCRIPTION
**Pull request by usamaidrsk**
**Explain what this PR does?**

This includes the navigation toolbar with a drawer (that is responsive  to screen sizes) at the right, as well as the footer 

**Propose Change**

- [ ] Bug fix (fixes an issue)
- [ ] Chore (small new feature added to the project)
- [x] New feature (change adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

**Motivation? (required)**

The navigation bar and footer shall be  displayed at any page of the project

**Provide test plan?(required)**

N/A

**Any background context you want to provide?**

N/A

**What are the relevant Trello/Pivotal/Jira/Github)**

[Task link](https://trello.com/c/6pHkVjG0/70-design-a-navigation-bar-and-the-footer)

**Screenshots (if appropriate)**
footer
galaxy
ipad

**Questions:**

N/A

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9

### CODE REVIEW

**Review by fahdjamy — CHANGES_REQUESTED** [review]
please provide a screenshot for this UI task you've implemented and we will go from there.

**Review by fahdjamy — CHANGES_REQUESTED** [review]
Please remove the footer.
Our footer will look something different from that.
look at [stripe's](https://stripe.com/) footer, that's how our footer will kind of look like.

Remove the drawer icon on the navbar as well.
Try to center the content.

**Comment by huxaiphaer** [comment]
Good work @usamaidrsk , kindly work on @FahdJamy feedback

**Comment by huxaiphaer** [comment]
@usamaidrsk and @bdllhdrss3 , resolve these conflicts

**Review by fahdjamy — APPROVED** [review]
LGTM

**Pull request merged**
